import React from "react";
import FullLayout from "../../src/layouts/FullLayout";
import theme from "../../src/theme/theme";
import { ThemeProvider } from "@mui/material/styles";
import Head from "next/head";
import { Grid } from "@mui/material";
import mongoose from "mongoose";
import Order from "../../models/Order";
import Allorders from "../../src/components/dashboard/Allorders";

const AllOrders = ({ orders }) => {
  return (
    <>
      <Head>
        <title>streetWear.com:admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <style jsx global>{`
          footer {
            display: none;
          }
          content {
            display: none;
          }
        `}</style>
        <FullLayout>
          <Grid container spacing={0}>
            <Grid item xs={12} lg={12}>
              <Allorders orders={orders} />
            </Grid>
          </Grid>
        </FullLayout>
      </ThemeProvider>
    </>
  );
};

// fetching the data from the mongodb
export async function getServerSideProps(context) {
  let error = null;

  if (!mongoose.connections[0].readyState) {
    await mongoose.connect(process.env.MONGO_URI);
  }
  // fetch the single item with the unique slug
  let orders = await Order.find();

  return {
    props: { orders: JSON.parse(JSON.stringify(orders)) }, // will be passed to the page component as props
  };
}
export default AllOrders;
